baseURL: https://matusnovak.github.io/doxybook2/hugo-learn
languageCode: en-us
title: Doxybook2 Example
theme: hugo-theme-learn
pygmentsUseClasses: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "tango"
