[[main]]
  name = "Documentation"
  identifier = "documentation"
  url = "/documentation/"
  weight = 20

[[main]]
  name = "Code Reference"
  identifier = "code"
  url = "/documentation/code/index_classes"
  parent = "documentation"
  weight = 40

[[main]]
  name = "Tutorials"
  identifier = "tutorials"
  url = "/documentation/tutorials/the_gambit_interface"
  parent = "documentation"
  weight = 20

[[documentation]]
  name = "Installation"
  identifier = "installation"
  url = "/documentation/installation/introduction/"
  weight = 10
  
[[documentation]]
  name = "Tutorials"
  identifier = "tutorials"
  url = "/documentation/tutorials/the_gambit_interface"
  weight = 20

[[documentation]]
  name = "Physics"
  identifier = "physics"
  url = "/documentation/physics/analyses"
  weight = 30

[[documentation]]
  name = "Help"
  identifier = "help"
  url = "/documentation/help/common_problems_and_questions"
  weight = 40

[[documentation]]
  name = "Code Reference"
  identifier = "code"
  url = "/documentation/code/index_classes"
  weight = 50

[[main]]
  name = "Installation"
  identifier = "installation"
  url = "/documentation/installation/introduction/"
  parent = "documentation"
  weight = 10

[[main]]
  name = "Physics"
  identifier = "physics"
  url = "/documentation/physics/analyses"
  parent = "documentation"
  weight = 20

[[main]]
  name = "Help"
  identifier = "help"
  url = "/documentation/help/common_problems_and_questions/"
  parent = "documentation"
  weight = 30

[[main]]
  name = "Community"
  identifier = "community"
  weight = 30

[[main]]
  name = "Wiki"
  url = "https://github.com/GambitBSM/wiki"
  logo = "/static/private.png"
  parent = "community"
  weight = 10

[[main]]
  name = "Publications"
  url = "/community/publications/"
  parent = "community"
  weight = 20

[[main]]
  name = "Talks"
  url = "/community/talks/"
  parent = "community"
  weight = 30

[[main]]
  name = "Members"
  url = "/community/members/"
  parent = "community"
  weight = 40

[[main]]
  name = "Code of Conduct"
  url = "/community/code_of_conduct/"
  parent = "community"
  weight = 50

[[main]]
  name = "Contact"
  url = "/community/contact/"
  parent = "community"
  weight = 60

[[main]]
  name = "Releases"
  identifier = "releases"
  weight = 5

[[main]]
  name = "GAMBIT 2-6 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.6"
  parent = "releases"
  weight = 5

[[main]]
  name = "GAMBIT 2-5 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.5"
  parent = "releases"
  weight = 10

[[main]]
  name = "GAMBIT 2-4 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.4"
  parent = "releases"
  weight = 15

[[main]]
  name = "GAMBIT 2-3 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.3"
  parent = "releases"
  weight = 20

[[main]]
  name = "GAMBIT 2-2 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.2"
  parent = "releases"
  weight = 25

[[main]]
  name = "GAMBIT 2-1 ⧉"
  url = "https://github.com/GambitBSM/gambit_2.1"
  parent = "releases"
  weight = 30

[[main]]
  name = "All releases ⧉"
  url = "https://github.com/GambitBSM/gambit_2.6/tags"
  parent = "releases"
  weight = 35

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/GambitBSM"
  post = "v0.1.0"
  weight = 10

[[footer]]
   name = "License"
   url = "/license/"
   weight = 10
