name: Check links

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  check_links:
    runs-on: macos-latest
    steps:
      - name: Install muffet
        run: brew install muffet
      - name: Run muffet to test for dead links
        run: muffet --buffer-size=10000 --max-connections=10000 --max-connections-per-host=10000 --max-redirections=10000 --max-response-body-size=100000000000000000000 --color=always https://gambitbsm.github.io/
