name: Check links

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages build and deployment"]
    branches: [main, gh-pages]
    types:
      - completed

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Install lychee
        run: go get -u github.com/raviqqe/muffet/v2
      - name: Run lychee to test for dead links
        run: muffet https://gambitbsm.github.io/
