name: Check links

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages build and deployment"]
    branches: [main, gh-pages]
    types:
      - completed

jobs:
  check_links:
    runs-on: macos-latest
    steps:
      - name: Install muffet
        run: brew install muffet
      - name: Run muffet to test for dead links
        # run: muffet https://gambitbsm.github.io/
        run: muffet --help
