name: Check links

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages build and deployment"]
    branches: [main, gh-pages]
    types:
      - completed

jobs:
  check_links:
    runs-on: macos-latest
    steps:
      - name: Install lychee
        run: brew install lychee
      - name: Run lychee to test for dead links
        run: lychee --no-progress --format detailed https://gambitbsm.github.io/
