name: Build and deploy site

on:
  repository_dispatch:
    types: [documentation_rebuilt]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Cache npm packages
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      #- name: Remove license.md
      #  run: cd content/en/documentation/_static/collapsible-lists
      #    && rm LICENSE.md

      #- name: Commit changes
      #  run: git config --local user.email "test@github.com"
      #    && git config --local user.name "GitHub Action test"
      #    && git add --all
      #    && git commit -m "Deleted problematic LICENSE.md"
      #    && git push

      - name: Install npm dependencies
        run: npm install

      # - name: Check for linting errors
      #  run: npm test

      - name: Build production website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: main_development
      
      - name: Deploy redirect 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redirect
          keep_files: true
